#!/usr/bin/env node
// Bundles ../corpus/catalog.json and worker/prompts/*.txt into src/corpus_data.ts so the
// Worker can serve them without a round-trip. Workers don't have filesystem access at
// runtime, so this runs at build time (see package.json's "dev"/"deploy" scripts) and the
// generated file is gitignored -- it's derived data, regenerate it, don't hand-edit it.
//
// The full document TEXT (corpus/sources/*.md) is NOT bundled here -- see upload_corpus.mjs.
// Bundling all document text directly into the JS bundle was the original approach and broke
// down at real scale: Workers cap script size at 3 MiB (free) / 10 MiB (paid) compressed, and
// at the corpus's actual measured per-document average (~61KB gzip), that ceiling arrives
// around ~48 documents on the free tier -- well before the ~170-230 document target. The
// catalog stays bundled because it's small by design (SPEC.md 3 targets ~40-60K tokens for
// the whole thing) and every query needs it for routing regardless of which sources get
// selected; individual documents only get fetched for the 1-6 sources actually selected per
// query, so fetching them from R2 at request time doesn't cost anything extra per query that
// bundling would have saved.
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "..");
const CATALOG_PATH = join(REPO_ROOT, "corpus", "catalog.json");
const SOURCES_DIR = join(REPO_ROOT, "corpus", "sources");
const PROMPTS_DIR = join(__dirname, "prompts");
const WIDGET_PATH = join(REPO_ROOT, "web", "widget.js");
const OUT_PATH = join(__dirname, "src", "corpus_data.ts");

const catalog = JSON.parse(readFileSync(CATALOG_PATH, "utf-8"));
const routePrompt = readFileSync(join(PROMPTS_DIR, "route.txt"), "utf-8");
const answerPrompt = readFileSync(join(PROMPTS_DIR, "answer.txt"), "utf-8");
const widgetJs = readFileSync(WIDGET_PATH, "utf-8");

const sourceFiles = new Set(
  readdirSync(SOURCES_DIR)
    .filter((f) => f.endsWith(".md"))
    .map((f) => f.slice(0, -3)),
);
const missing = catalog.map((c) => c.id).filter((id) => !sourceFiles.has(id));
if (missing.length) {
  console.error(`build_corpus: catalog references sources with no .md file: ${missing.join(", ")}`);
  process.exit(1);
}

const out = `// GENERATED by build_corpus.mjs from corpus/catalog.json, worker/prompts/*.txt, and
// web/widget.js. Do not hand-edit -- edit those and re-run \`npm run build:corpus\`.
// Document TEXT is NOT here -- it's in R2, uploaded via upload_corpus.mjs / npm run upload:corpus.
import type { CatalogEntry } from "./catalog_types";

export const CATALOG: CatalogEntry[] = ${JSON.stringify(catalog, null, 2)};

export const ROUTE_PROMPT = ${JSON.stringify(routePrompt)};

export const ANSWER_PROMPT = ${JSON.stringify(answerPrompt)};

export const WIDGET_JS = ${JSON.stringify(widgetJs)};
`;

writeFileSync(OUT_PATH, out);
console.log(`build_corpus: wrote ${OUT_PATH} (${catalog.length} catalog entries)`);
