#!/usr/bin/env node
// Bundles ../corpus/catalog.json and ../corpus/sources/*.md into src/corpus_data.ts so the
// Worker can serve them without a KV/R2 round-trip. Workers don't have filesystem access at
// runtime, so this runs at build time (see package.json's "dev"/"deploy" scripts) and the
// generated file is gitignored -- it's derived data, regenerate it, don't hand-edit it.
//
// This bundling approach is fine at today's corpus size (~1.2MB across 6 sources) but won't
// scale indefinitely -- if the corpus grows toward SPEC.md's ~100-item target, move
// corpus/sources/*.md to R2 and fetch at request time instead of inlining everything into
// the JS bundle.
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "..");
const CATALOG_PATH = join(REPO_ROOT, "corpus", "catalog.json");
const SOURCES_DIR = join(REPO_ROOT, "corpus", "sources");
const PROMPTS_DIR = join(__dirname, "prompts");
const OUT_PATH = join(__dirname, "src", "corpus_data.ts");

const catalog = JSON.parse(readFileSync(CATALOG_PATH, "utf-8"));
const routePrompt = readFileSync(join(PROMPTS_DIR, "route.txt"), "utf-8");
const answerPrompt = readFileSync(join(PROMPTS_DIR, "answer.txt"), "utf-8");

const sources = {};
for (const file of readdirSync(SOURCES_DIR)) {
  if (!file.endsWith(".md")) continue;
  const id = file.slice(0, -3);
  sources[id] = readFileSync(join(SOURCES_DIR, file), "utf-8");
}

const missing = catalog.map((c) => c.id).filter((id) => !(id in sources));
if (missing.length) {
  console.error(`build_corpus: catalog references sources with no .md file: ${missing.join(", ")}`);
  process.exit(1);
}

const out = `// GENERATED by build_corpus.mjs from corpus/catalog.json, corpus/sources/*.md, and
// worker/prompts/*.txt. Do not hand-edit -- edit those and re-run \`npm run build:corpus\`.
import type { CatalogEntry } from "./catalog_types";

export const CATALOG: CatalogEntry[] = ${JSON.stringify(catalog, null, 2)};

export const SOURCES: Record<string, string> = ${JSON.stringify(sources, null, 2)};

export const ROUTE_PROMPT = ${JSON.stringify(routePrompt)};

export const ANSWER_PROMPT = ${JSON.stringify(answerPrompt)};
`;

writeFileSync(OUT_PATH, out);
console.log(`build_corpus: wrote ${OUT_PATH} (${catalog.length} catalog entries, ${Object.keys(sources).length} source files)`);
